/**
 * GeneratedPreviewPayload
 *
 * The single data contract between the generation pipeline and the
 * portal preview UI.  Every dynamic value rendered in the 3 preview
 * screens (Login, Home, Messages) must be sourced from this type.
 *
 * ── Relationship to the pipeline ──────────────────────────────────
 * The API route produces `PortalData` + `RawOutputs`.
 * `page.tsx` transforms those into a `GeneratedPreviewPayload` before
 * passing it to `<PortalPreview>`.  The preview components never
 * import or reference `PortalData` / `RawOutputs` directly.
 *
 * ── Extending for future screens ──────────────────────────────────
 * If a new screen needs a value that doesn't exist yet, add it to
 * the relevant group below and update the adapter in `page.tsx`.
 * Do NOT add UI-only constants here (static labels, placeholder
 * text, icon paths).
 */

// ─── Branding ────────────────────────────────────────────────────
/** Company identity assets produced by the scraping pipeline. */
export interface PreviewBranding {
  /** Cleaned company name.  Used in: sidebar, top-bar headers, message sender. */
  companyName: string;

  /**
   * Square icon / favicon URL (≤ 300×300).
   * Used in: sidebar logo, login form logo, message-1 avatar.
   * Fallback: first letter of `companyName` rendered as initial.
   */
  logoUrl: string | null;

  /**
   * Dominant background color of the square icon (hex).
   * Used as the message-avatar container fill so the logo
   * blends seamlessly with its own background.  null when
   * the background is transparent or ambiguous.
   */
  squareIconBg: string | null;

  /**
   * Full horizontal logo URL (min 180 px height).
   * Currently unused in the 3 preview screens but kept for future
   * screens (e.g. email header, social card).
   */
  fullLogoUrl: string | null;
}

// ─── Theme ───────────────────────────────────────────────────────
/** Color tokens derived from the quality-gate pipeline. */
export interface PreviewTheme {
  /** Primary brand surface: sidebar bg, login button bg. */
  sidebarBackground: string;

  /**
   * Accessible text on `sidebarBackground`: sidebar labels,
   * sidebar icon `fill`, login button text.
   */
  sidebarText: string;

  /**
   * Brand accent color.
   * Not actively used in the current 3 screens but reserved for:
   * - Hover / focus rings
   * - Links inside portal content
   * - Future screen highlights
   */
  accent: string;
}

// ─── Images ──────────────────────────────────────────────────────
/** Generated / scraped imagery used as decorative fills. */
export interface PreviewImages {
  /**
   * Login screen right-side hero image.
   * Fallback: `/assets/Images/Rectangle 34624749.png` (spiral staircase).
   */
  loginHeroImageUrl: string | null;

  /**
   * Dashboard screen hero / banner image.
   * Currently a static placeholder; the pipeline may fill it later.
   * Fallback: none (show placeholder zone).
   */
  dashboardHeroImageUrl: string | null;

  /**
   * Social / OG share image.
   * Not rendered in any of the 3 screens but kept here so
   * the pipeline output has a single shape.
   */
  socialImageUrl: string | null;
}

// ─── Copy ────────────────────────────────────────────────────────
/** Text content generated from scraped website context. */
export interface PreviewCopy {
  /**
   * The company's welcome message shown in the Messages screen
   * (message bubble #1, from the company).
   *
   * Generated by the pipeline using the company's website context.
   * Generation logic TBD — for now assume this string is already
   * present in the payload by the time the preview renders.
   *
   * Example: "Welcome to the BrandMages portal! We're excited to
   * collaborate with you on the BlackForge project."
   */
  welcomeMessageText: string;
}

// ─── Root payload ────────────────────────────────────────────────
export interface GeneratedPreviewPayload {
  branding: PreviewBranding;
  theme: PreviewTheme;
  images: PreviewImages;
  copy: PreviewCopy;
}

// ─── Adapter ─────────────────────────────────────────────────────
/**
 * Transforms the raw pipeline output (`PortalData` + `RawOutputs`)
 * into the preview payload.
 *
 * This is the ONLY place that knows about both shapes.
 * Call it once in `page.tsx` when the generation completes.
 */
import type { PortalData, RawOutputs } from "./api";

/** Static fallback for `copy.welcomeMessageText` until the pipeline generates it. */
const DEFAULT_WELCOME_MESSAGE =
  "Welcome! We're excited to work together. This is your portal — feel free to look around and let us know if you need anything.";

export function toPreviewPayload(
  data: PortalData,
  _rawOutputs: RawOutputs | null
): GeneratedPreviewPayload {
  // Square-slot logo: only use the processed 300×300 square icon.
  // fullLogo is typically a wide wordmark that renders poorly in small square
  // containers (20–40px). If squareIcon is empty (rejected by quality gate or
  // processing failed), go straight to null → CompanyLogo shows clean initials.
  // Uses || (not ??) so empty strings from failed processing fall through.
  const logoUrl = data.images.squareIcon || null;

  return {
    branding: {
      companyName: data.companyName,
      logoUrl,
      squareIconBg: data.images.squareIconBg ?? null,
      fullLogoUrl: data.images.fullLogo || data.images.rawLogoUrl || null,
    },
    theme: {
      sidebarBackground: data.colors.sidebarBackground,
      sidebarText: data.colors.sidebarText,
      accent: data.colors.accent,
    },
    images: {
      loginHeroImageUrl: data.images.loginImage,
      dashboardHeroImageUrl: data.images.dashboardImage,
      socialImageUrl: data.images.socialImage,
    },
    copy: {
      /**
       * TODO: Replace with pipeline-generated text once the
       * generation logic is implemented.  For now, fall back to
       * a generic welcome string so the Messages screen is never
       * empty.
       */
      welcomeMessageText: DEFAULT_WELCOME_MESSAGE,
    },
  };
}
